# ───────────────────────────────────────────────
# 1) 80포트(http)로 들어오는 모든 요청을 https로 리다이렉션
server {
    listen 80;
    server_name api.pozit.kr;

    # Certbot 인증 및 자동 갱신 경로
        location ^~ /.well-known/acme-challenge/ {
            root /var/www/certbot;
            default_type text/plain;
            try_files $uri =404;
        }
     # 나머지 요청은 HTTPS로 리다이렉트
        location / {
            return 301 https://api.pozit.kr$request_uri;
        }
}

# ───────────────────────────────────────────────
# 2) https://로 들어오는 요청을 서비스 중인 포트로 연결
server {
    listen 443 ssl http2;
    http2 on;

    # ssl 인증서 적용
    ssl_certificate /etc/letsencrypt/live/api.pozit.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.pozit.kr/privkey.pem;

    location / { # location 이후 특정 Url을 처리하는 방법을 정의 (여기서는 / -> 즉, 모든 request)
         proxy_pass http://server:8080; # Request에 대해 어디로 리다이렉트하는지 작성. 8443 -> 자신의 springboot app 이사용하는 포트
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
    }
}


# 등록되지 않은 HTTP 도메인 차단
server {
    listen 80 default_server;
    server_name _;
    return 404;
}

# 등록되지 않은 HTTPS 도메인 차단
server {
    listen 443 ssl default_server;
    server_name _;

    ssl_certificate /etc/letsencrypt/live/api.pozit.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.pozit.kr/privkey.pem;

    return 404;
}